### PR TITLE
Drop Julia-0.6 and add NamedTuples (fix 55)

### LINKED ISSUE #55: Keyword constructor for named tuples
This is intended to be a discussion point for an implementation of https://discourse.julialang.org/t/macro-challenge-factory-for-creating-named-tuples/9748/20  The idea would be for a v0.7 factor for creating named tuples with defaults in a type-safe way.

### PR DESCRIPTION
**Pull request by mauro3**
Fixes #55.  This implements NamedTuples with default values as suggested by @jlperla on [Discourse](https://discourse.julialang.org/t/macro-challenge-factory-for-creating-named-tuples/9748):
```julia
MyNT = @with_kw (a=1, b="test", w=:uu)
MyNT()==(a=1, b="test", w=:uu)
```
This is an alternate implementation of @ArnavSood's PR #62, which I started working on before that PR and was actually close to finished.  So I finished it here, sorry.

This also drops Julia 0.7, for which I don't really want to add new features at this stage.  If someone feels strongly about this, they are welcome to take this PR and re-add Julia 0.6 to it.

### CODE REVIEW

**Comment by jlperla** [comment]
Great!  A few comments:
- I think there is still a scoping issue.  In particular, try this:
```
using Parameters
@with_kw (a=1, b="test", w=:uu) #no problem
q = 2
@with_kw (q=q) #weird error... expanding the q?
@with_kw (q2=q) #weird error... expanding the q?  Not just the q=q issue.
```
- More generally, I think that Arnav's test: https://github.com/mauro3/Parameters.jl/issues/55#issuecomment-401518973 is a great one.
- It doesn't seem to support anonymous functions
```
julia> @with_kw (m2 = x-> x)
ERROR: LoadError: only works on type-defs or named tuples.  (Make sure to have a space after @with_kw`.)
S
```
- The `@with_kw (a=1, b="test", w=:uu)` signature is very easy to confuse with the `@with_kw(a=1, b="test", w=:uu)` signature, and I have already made the mistake several times.
  - Is there any reason not to support `@with_kw(a=1, b="test", w=:uu)` as well?  Unlike the macro in front of a structure (where it doesn't look like w function), I think it is very reasonable to interpret this as a function returning a factory, rather than a macro operating on a named tuple?
  - Worst case, I think that having an error message more clear than
```
julia> f = @with_kw(a=1, b="test", w=:uu)
ERROR: LoadError: MethodError: no method matching @with_kw(::LineNumberNode, ::Module, ::Expr, ::Expr, ::Expr)
Closest candidates are:
  @with_kw(::LineNumberNode, ::Module, ::Any) at C:\Users\jlperla\.julia\dev\Parameters\src\Parameters.jl:612
in expression starting at REPL[5]:1
```
would help. (Note that the error message for a single named-tuple argument is different, and does mention the space).
- With the interpretation of a function returning a factory, what do you think about an interface using a generated function?  i.e., could call it as `with_kw(a = 1, b = "test", w = :uu)` or a separate (generated) function for named tuples, `nt_kw(a=1, b="test", w=:uu)`?  I think this would be very clear for usage.

**Comment by jlperla** [comment]
@Nosferican for the QuantEcon lectures, are you targeting v0.7 directly, or are you planning to work in v0.6 for now and convert over later?  I think this may impact whether we think that v0.6 support is necessary, since this is crucial to support your rewrite?

**Comment by jlperla** [comment]
Another question in the current implementation.... lets say that we have a function `expensive_operation()` for determining the default value, it would be great if it didn't need to run the expensive operation.  Using the original implementation from @bramtayl you can see that
```
using NamedTuples, MacroTools
macro with_kw(args...)
           splits = map(args) do arg
               @match arg begin
                   (a_ = b_) => (a, b)
                   any_ => error("All arguments must be assignments")
               end
           end
           esc(:(
               (;$(map(splits) do pair
                   Expr(:kw, pair[1], pair[2])
               end...),) ->
               $NamedTuples.@NT($(map(splits) do pair
                   Expr(:kw, pair[1], pair[1])
               end...))
           ))
       end
function expensive_operation()
       @show "Expensive!"
       return 5
end
```
Then,
```
julia> nt1 = nt_generator(a=3) #Doesn't run expensive_operation()
(a = 3, b = 1)

julia> nt2 = nt_generator()
"Expensive!" = "Expensive!"
(a = 5, b = 1)
```
I think this is an extremely important feature for a tuple generator.

**Comment by mauro3** [comment]
Just one quick remark you need a comma in tuple construction:
```                                                                                                                                                                      
julia> (m2 = x-> x)                                                                                                                                                      
#24 (generic function with 1 method)                                                                                                                                     
                                                                                                                                                                         
julia> (m2 = x-> x,)                                                                                                                                                     
(m2 = getfield(Main, Symbol("##26#27"))(),)                                                                                                                              
```

(The rest I'll read tonight or tomorrow)

**Comment by jlperla** [comment]
@mauro3 Sounds great.  Once you think through some of this, Arnav can help by expanding the tests and documentation.

**Comment by ArnavSood** [comment]
Do you think it's worth changing the name on this? That way, we don't need the comma (which I think is to give us a `:tuple` value of `typedef.head`), and we can be clean about (say) handling the cases with/without spaces. 

Something like `@nt_kw` gets the message across.

**Comment by jlperla** [comment]
> Do you think it's worth changing the name on this? 

@mauro3  I think this comes down to mental model of the macro.... Certainly the `@kw_arg struct ...` is interpreted as adding features to a struct, but I don't think that is the right interpretation here.  For one thing, what is returned is not a tuple, but a function that returns a tuple (unlike the results of `@kw_arg struct` which returns a struct with added constructors/features).

I think the better mental model is of a function which returns a named tuple factory.  In that case, it may make sense to have a different name, and perhaps even to implement it as a generated function rather than a macro.

**Comment by ArnavSood** [comment]
To be honest, I was thinking something similar (that leaving this as a macro might be more of a hassle than it's worth). Mainly because this is something that needs access to the values associated with symbols. And trying to keep those values straight in "macro-time" (parse time?) has been challenging. 

Don't know much about generated functions (yet!). Will defer to you and @mauro3 on how to proceed.

**Comment by mauro3** [comment]
Concerning the comments:
- the non-space syntax is a no-go for me.  The macro should act on a NamedTuple, thus the space is needed.  I think this is a distinction worth hammering home.  I added more informative error messages (also addressing the potential confusion with forgetting the trailing comma on single field tuples):
```julia
julia> @with_kw(a=1)                                                                                                                                                     
ERROR: LoadError: Only works on type-defs or named tuples.                                                                                                               
Make sure to have a space after `@with_kw`, e.g. `@with_kw (a=1,)
Also, make sure to use a trailing comma for single-field NamedTuples.
                                                                                                                                                                         
Stacktrace:                                                                                                                                                              
 [1] error at ./error.jl:33 [inlined]                                                                                                                                    
 [2] with_kw(::Any, ::Module, ::Bool) at /home/mauro/.julia/dev/Parameters/src/Parameters.jl:299                                                                         
 [3] @with_kw(::LineNumberNode, ::Module, ::Any) at /home/mauro/.julia/dev/Parameters/src/Parameters.jl:616                                                              
in expression starting at REPL[2]:1
                                                                                                                                                                         
julia> @with_kw(a=1, b=2)                                                                                                                                                
ERROR: LoadError: Only works on type-defs or named tuples.                                                                                                               
Did you try to construct a NamedTuple but omitted the space between the macro and the NamedTuple?
Do `@with_kw (a=1, b=2)` and not `@with_kw(a=1, b=2)`.

Stacktrace:
 [1] error(::String) at ./error.jl:33                                                                                                                                    
 [2] @with_kw(::LineNumberNode, ::Module, ::Vararg{Any,N} where N) at /home/mauro/.julia/dev/Parameters/src/Parameters.jl:623                                            
in expression starting at REPL[3]:1
```

- I don't understand the proposed generated function interface.  But I feel the interface in this PR is consistent with the rest of the interface.
- Concerning the "expensive function": I think it is best to leave as is.  This is also consistent with how kw-args for functions work.  If evaluation is desired beforehand, then the user can do it explicitly.  Also, note that if the expensive function has previous fields as arguments, then the situation gets tricky as one would need to check that previous arguments are at their default or otherwise evaluate the expensive function again.

**Comment by jlperla** [comment]
I think I now understand the disconnect in how we have been thinking about it.    Just to be clear, let me see if I can restate your approach.  The current `@with_kw` operates on a potentially parametric `struct` and adds in convenience constructors, spitting out a new type.  I completely understand your perspective that the best analogy to named tuples is that it operates on a named tuple.  Hence, having things like `@with_kw (a = 1, b = "test")` make complete sense to be consistent with the rest of the interface.

Now the issue with that analogy are:
- The "return type"
  - It doesn't really return anything, but modifies the `struct` definition of the typedef.  In particular  `@with_kw struct` is a (potentially parametric) `struct`
  - The return type (actually returned) as you have proposed for the `@with_kw  (a = 1, b = "test")` is a function returning named tuples.  So I find that interface to be subtle different than the current structure... but I can move past that as semantics of the interface is your business.

- The bigger issue is that while `struct` can be parametric, named tuples are not in this sense.  To be more concrete, here is a typical example of how I would use the current structure with a struct.
```julia
julia> using Parameters, Distributions
julia> @with_kw struct T{F, D}
              f::F = x-> x
              d::D = Normal(0.0, 1.9)
       end
T
julia> t = T(f = x -> x^2)
T{##17#18,Distributions.Normal{Float64}}
  f: #17 (function of type ##17#18)
  d: Distributions.Normal{Float64}
julia> t.f(2)
4
julia> t2 = T(d = Exponential(1.0))
T{##10#16,Distributions.Exponential{Float64}}
  f: #10 (function of type ##10#16)
  d: Distributions.Exponential{Float64}
julia> pdf(t.d, 0.1)
0.20967900591758526
```
Note that
```julia
julia> typeof(t)
T{##17#18,Distributions.Normal{Float64}}
julia> typeof(t2)
T{##10#16,Distributions.Exponential{Float64}}
```
Now, lets go to Named Tuples.... In your interface
```julia
T_factory = @with_kw  (f = x-> x,  d = Normal(0.0, 1.9))
```
Now, when I look at that, it sure looks to me like `T_factory` should always spit out named tuples of a type like
```julia
NamedTuple{(:f, :d), Tuple{##17#18, Distributions.Normal{Float64}}
```
But that is not what I want.  This isn't a corner case of requirements, as swapping out the distribution and function is precisely why I want to have a named tuple generator for defaults in the lecture notes.

I think this may be at the heart of why I couldn't get some of the other tests to work in your current structure... though I could be missing something?

Now, consider the alternative approach (with a different name!) where the semantics are that the macro creates a named tuple factory rather than operating on a nameed tuple.  That is.
```julia
T_factory = @nt_factory(f = x-> x,  d = Normal(0.0, 1.9))
t = T_factory(d = Exponential(1.0)
```
Of course, the name could be anything (except `@with_kw`, which I agree is completely inconsistent without the space). But I think that the semantics are very clear.  My thought on a generated function was that we can really think of this as a higher-order function, and hence it would be nice to be able to call it as `T_factory = nt_factory(f = x-> x,  d = Normal(0.0, 1.9))`, but that is not especially important.

The @bramtayl implementation of `@with_kw` has exactly these semantics, handles the (crucial) parametric cases well, and the only known bug is of the `@with_kw(f=f)` variety.

**Comment by mauro3** [comment]
Thanks for the careful explanation!  I will need to ponder it some.  My idea was, that NamedTuples are to structs like anonymous functions are to normal functions.  Using this analogy, I think the syntax as I setup makes ok "sense".

Aside, I'm not quite sure that you realize that:

1) with this PR this works:
```julia
julia> MyNT = @with_kw (a=1, b="a")                                                                                                                                      
#6 (generic function with 2 methods)                                                                                                                                 

julia> MyNT(b=9.0)                                                                                                                                                       
(a = 1, b = 9.0)                                                                                                                                                         
```
I sure don't want to have `MyNT` restricted to produce `NamedTuple{(:a, :b),Tuple{Int64,String}}` either.

2) the end result is the same as you describe. The `MyNT` is the named-tuple factory.

(Have you given this PR a spin?)

**Comment by jlperla** [comment]
> (Have you given this PR a spin?)

I did.  But... I begrudgingly admit that I didn't after you corrected my issue with the trailing comma... 

It turns out that it was the entirety of my issues!  To be clear, you are correct that the following works totally fine.
```julia
julia> MyNT = @with_kw (f=x->x, y = [1 2 3])
#3 (generic function with 2 methods)

julia> typeof(MyNT())
NamedTuple{(:f, :y),Tuple{getfield(Main, Symbol("##5#8")),Array{Int64,2}}}

julia> typeof(MyNT(f=x-> x^2))
NamedTuple{(:f, :y),Tuple{getfield(Main, Symbol("##10#11")),Array{Int64,2}}}

julia> typeof(MyNT(f=x-> x^2, y = [1.0 2.0; 3.0 4.0]))
NamedTuple{(:f, :y),Tuple{getfield(Main, Symbol("##12#13")),Array{Float64,2}}}
```
Furthermore it doesn't seem to have that weird scoping issue as before.
```julia
julia> f = x -> x^3
#14 (generic function with 1 method)

julia> nt = MyNT(f=f, y = 4)
(f = getfield(Main, Symbol("##14#15"))(), y = 4)

julia> nt.f(3)
27

julia> typeof(nt)
NamedTuple{(:f, :y),Tuple{getfield(Main, Symbol("##14#15")),Int64}}
```
A quick check on performance (sorry, `BenchmarkTools.jl` isn't working for me on the nighlies) shows it is ballpark the same as just contructing a named tuple.
```julia
julia> @time MyNT(f=f, y=4)
  0.000040 seconds (11 allocations: 416 bytes)
(f = getfield(Main, Symbol("##14#15"))(), y = 4)

julia> @time MyNT()
  0.000004 seconds (6 allocations: 288 bytes)
(f = getfield(Main, Symbol("##5#8"))(), y = [1 2 3])

julia> @time (f=f, y=4)
  0.000021 seconds (10 allocations: 400 bytes)
(f = getfield(Main, Symbol("##14#15"))(), y = 4)
```

So, as far as I am concerned, I think this fulfills all of the essential requirements we had.  I had the very different perspective on the semantics of the function, but am open minded to your approach (though consider reading my perspective as well in the previous post).

Would you like @ArnavSood to add any documentation or tests?

**Comment by jlperla** [comment]
I am not yet sure about the need for v0.6... but do you suspect it is possible with the current infrastructure?

Looking at the code, it appears that the key lines are
```julia
   nt = Expr(:tuple, nt...)
    NT = gensym(:NamedTuple_kw)
    quote
        $NT = (; $(kwargs...)) -> $nt
        (::typeof($NT))($(args...)) = $nt
        $NT
    end
```
If so, assuming that a `using NamedTuples` is there (which is working in v0.7) I am not sure what change this would require.... is it just the `Expr(:tuple, nt...)` that requires modification.  If so, the structure is unclear.  For what it is worth,
```julia

julia> dump(:((a=1, b=2.0)))
Expr
  head: Symbol tuple
  args: Array{Any}((2,))
    1: Expr
      head: Symbol =
      args: Array{Any}((2,))
        1: Symbol a
        2: Int64 1
    2: Expr
      head: Symbol =
      args: Array{Any}((2,))
        1: Symbol b
        2: Float64 2.0

julia> dump(:(@NT(a=1, b=2.0)))
Expr
  head: Symbol macrocall
  args: Array{Any}((4,))
    1: Symbol @NT
    2: LineNumberNode
      line: Int64 1
      file: Symbol REPL[43]
    3: Expr
      head: Symbol =
      args: Array{Any}((2,))
        1: Symbol a
        2: Int64 1
    4: Expr
      head: Symbol =
      args: Array{Any}((2,))
        1: Symbol b
        2: Float64 2.0
```

**Comment by mauro3** [comment]
Cool! 
- I'll think about the interface. 
- Documentation would be great!
- 0.6 support should be possible like so:
```
    quote
        $NT = (; $(kwargs...)) -> @NT $nt
        (::typeof($NT))($(args...)) = @NT $nt
        $NT
    end
```
+ adding all the stuff back in which I deleted (foolishly not preserved as a single commit).

**Comment by ArnavSood** [comment]
This could be nitpicking, but it looks like we still have one of the scoping issues from the earlier tests; i.e.

```
julia> y = 3
3

julia> test = @with_kw (y = 4, c = y)
#10 (generic function with 2 methods)

julia> test()
(y = 4, c = 4)
```

Maybe this isn't a realistic use case, though.

**Comment by jlperla** [comment]
> This could be nitpicking, but it looks like we still have one of the scoping issues from the earlier tests

I think the key question here is consistency.  The behavior seems more consistent with a "function" interpretation of the macro rather than operating on a named tuple.  That is, unless I am missing something,
```julia
julia> y=3
3

julia> (y=4, c=y)
(y = 4, c = 3)

julia> g(y=4, c=y) = (y=y,c=c)
g (generic function with 3 methods)

julia> g()
(y = 4, c = 4)
```

That said, I don't think it is a blocker, though, as long as it is documented.  It might be an odd corner case of named tuples.

My vote would be to add 0.6 support back into the PR if at all possible, and have it use `NamedTuples` with 0.6.  It just isn't stable to use 0.7 yet, and I am not sure how long it will realistically take before all of the key dependent libraries are upgraded/stable...

**Comment by ArnavSood** [comment]
Yeah, I agree that it's more reminiscent of a function call. I think implication of `@with_kw (y = 4, c = y)` is that the named tuple `(y = 4, c = y)` already "exists," and we're just modifying/packaging it somehow.

**Comment by mauro3** [comment]
It's consistent with how the rest of Parameter works:
```
julia> y = 3                                                                                                                                                             
3                                                                                                                                                                        

julia> @with_kw struct A
       y = 4
       c = y
       end                                                                                                                                                               
A                                                                                                                                                                        

julia> A()                                                                                                                                                               
A                                                                                                                                                                        
  y: Int64 4                                                                                                                                                             
  c: Int64 4                                                                                                                                                             
```
which is how keyword-arguments work.  Keyword constructors of NT and structs need to work identically, otherwise they cannot be drop-ins for each other.

**Comment by ArnavSood** [comment]
@mauro3 Sounds good. And I think if we document this, then it's something people can plan around (i.e., "try not to use the same symbol across assignments, unless you know what you're doing." The common use case like @jlperla said is probably `(..., f = f, g = g, ...)`, so it's good that that works.

**Comment by jlperla** [comment]
> which is how keyword-arguments work
Consistent with "something" is good enough for me.

@mauro3 We checked in with one of the key targets of the functionality, and they are targeting v0.7.  So, while I would love to be able to use this for v0.6 in the meantime (if it isn't much work for you) we can survive otherwise.

What can @ArnavSood do to help get this feature into a tagged release sooner rather than later?  He can add in a few extra tests and some examples int the docs.

**Comment by mauro3** [comment]
@jlperla:
- I thought a bit more about your generated function interface but I don't think that can work as kwargs do not participate in dispatch and thus neither in function-generation.
- I added Julia 0.6 support back in.

@ArnavSood, standard, kw-like approach the also has advantages:
```
struct A
a = 1
twice_a = 2*a
end
A(a=2) # A(2,4)
```

I'd say we merge this and then you can add some docs & extra tests in a separate PR.  That would be easiest. Sounds good?

**Comment by jlperla** [comment]
All sounds great

**Comment by ArnavSood** [comment]
@mauro3 Sounds good to me.

**Pull request merged**
