### PR TITLE
Fix errors and depwarns on 0.7

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by mauro3** [comment]
Thanks for looking into this!  There are test failures on 0.7:
https://travis-ci.org/mauro3/Parameters.jl/jobs/275674768

Are those expected?

**Comment by yuyichao** [comment]
It's from `DataStructures.jl` and will be fixed by https://github.com/JuliaCollections/DataStructures.jl/pull/329

**Comment by mauro3** [comment]
Thanks! I'll review this over the next few days.

**Comment by mauro3** [comment]
With the new DataStructures tag https://github.com/JuliaCollections/DataStructures.jl/releases/tag/v0.7.2 the tests now pass on Julia 0.7 (at least on Linux, the OSX builds take a bit longer as usual...).  Once OSX passes I'll merge. I will also bump the DataStructures version to 0.7.2 in a separate commit.

**Comment by mauro3** [comment]
DataStructures 0.7.2 does not work on Julia 0.5, so I'll leave the REQUIRE alone for now.

**Pull request merged**
